### ISSUE TITLE
SaveGameFree tries to delete output_log.txt

### ISSUE THREAD

**Issue by Sebadst** [BayatGames/SaveGameFree#11]
Hello,

I'm using this repo to handle my saves. So far so good when using the editor and with my Android build.
When I build on Windows however, and I try to execute the `.exe` there's an issue.
I am calling the `DeleteAll` method. The method tries to remove everything in the folder, including the `output_log.txt` which is by default put in that folder by Unity.
This makes the whole game crash, since it tries to delete a file that the game needs to access at every moment ( basically I have an IOException `Cannot access file output_log.txt because it is being used by another process`).
It also removes the `Analytics folder` that gets created, this doesn't let the game crash but I guess is not exactly intended.

I think we should either avoid having the saves in the same folder as the `output_log.txt` or explicitly ignore that file (and probably the Analytics folder)

**Comment by hasanbayatme** [comment]
Hi @Sebadst, thanks for reporting the issue.

Yes, the current workaround would be to use a subfolder for your `saves`, but in the later update, we would explicitly ignore the `Analytics` folder and `output_log.txt` file.

I'll keep this issue open so you can report further details related to the `DeleteAll` method until a release fixes the issue.
