### ISSUE TITLE
SamsungTVPlayer Obsolete in Unity 2017 and newer

### ISSUE THREAD

**Issue by JudgeGroovyman** [BayatGames/SaveGameFree#12]
**Describe the bug**
This warning appears in Unity 2019.4.20f1 (LTS) and based on the warning text it probably also appears in 2017.3+
`warning CS0618: 'RuntimePlatform.SamsungTVPlayer' is obsolete: 'SamsungTVPlayer export is no longer supported in Unity 2017.3+.'`

**To Reproduce**
1. Import the repo
2. See the warning in the console

**Expected behavior**
This warning should not appear and doesn't need to appear with the right Platform Dependent Preprocessor settings.

**Comment by hasanbayatme** [comment]
The latest release fixes the deprecation warnings and makes the package compatible with 2019.4 upwards.
