### ISSUE TITLE
UnityWebRequest.Send() is obsolete (which generates a warning)

### ISSUE THREAD

**Issue by JudgeGroovyman** [BayatGames/SaveGameFree#14]
**Describe the bug**
UnityWebRequest.Send() is obsolete and is used in `SaveGameFree/Scripts/SaveGameWeb.cs(578,17)`.  I received the following warning when importing SaveGameFree into Unity 2019.4.20f1 

`Assets/_PluginsMIT/SaveGameFree/Scripts/SaveGameWeb.cs(578,17): warning CS0618: 'UnityWebRequest.Send()' is obsolete: 'Use SendWebRequest.  It returns a UnityWebRequestAsyncOperation which contains a reference to the WebRequest object.'`

**When did it become obsolete?**
Looking at different versions of the documentation it looks like this became obsolete in 2017.2.  
1. [This 2019.4 documentation says its obsolete](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Send.html)
2. [This 2017.2 documentation says its obsolete](https://docs.unity3d.com/2017.2/Documentation/ScriptReference/Networking.UnityWebRequest.Send.html)
3. [This 2017.1 documentation says its ok (doesnt say its obsolete)](https://docs.unity3d.com/2017.1/Documentation/ScriptReference/Networking.UnityWebRequest.Send.html)

**What should it be replaced with?**
The Unity 2019.4 Documentation shows [how to do it the new way for a get](https://docs.unity3d.com/Manual/UnityWebRequest-RetrievingTextBinaryData.html) and [the same approach for post](https://docs.unity3d.com/Manual/UnityWebRequest-SendingForm.html) using that exact approach I have no errors or warnings in 2019.4.20f1 (and will submit a pull request momentarily) so it seems to work.  

**To Reproduce**
To get the warning just import the latest version of SaveGameFree into Unity 2019.4.20f1 and look at the warning in the console.  

**Additional context**
I'll submit a pull request with a proposal, and will make clear in the pull request that while my fix (which I took directly from the documentation and theres no ingenuity involved at all) solves the warning with no errors but I don't have a way to actually test the UnityWebRequest functionality.

**Comment by hasanbayatme** [comment]
#12
