### ISSUE TITLE
Want to get Json data

### ISSUE THREAD

**Issue by RaeesHaider72** [BayatGames/SaveGameFree#18]
I want to get the information like (Position, Rotation, Scaling and other custom information) of Multiple game objects and save that information as a JSON File. But, the issue I am facing right now that I am only getting information as a string. 
Can any one please guide me about this how can I get all information in a single file using this asset.

**Comment by hasanbayatme** [comment]
You can have a data model in which you can assign the position, rotation and scaling of each gameobject though a list:

```csharp
public class GameObjectData {

  public Vector3 position;
  public Quaternion rotation;
  public Vector3 scale;

}
```

And then have a list of them:

```csharp
public List<GameObjectData> gameObjectsData = new List<GameObjectData>();
```

Then add GameObjects to that list for later serialization:

```csharp
var gameObjectData = new GameObjectData();
gameObjectData.position = transform.position;
gameObjectData.rotation = transform.rotation;
gameObjectData.scale = transform.localScale;
this.gameObjectsData.Add(gameObjectData);
```

Now just call the save using the `gameObjectsData` list and it'll be saved to a single file.
