### ISSUE TITLE
Problem with Saver.Load

### ISSUE THREAD

**Issue by dkorobov2** [BayatGames/SaveGameFree#2]
Hi,

Thank you for this great resource. I have used the awake function as shown in the Demo to initialize save and load, but when I try calling Saver.Load in other places in my code, I get:

NullReferenceException: Object reference not set to an instance of an object
SaveGameFree.Saver.Save (System.Object obj, System.String fileName, ISerializer serializer, PathType savePath, System.String extension) (at Assets/SaveGameFree/Saver.cs:527)
SaveGameFree.Saver.Load[StripesData] (System.String fileName, ISerializer serializer, PathType savePath, System.String extension) (at Assets/SaveGameFree/Saver.cs:625)
SaveGameFree.Saver.Load[StripesData] (System.String fileName) (at Assets/SaveGameFree/Saver.cs:539)
GameManager.Start () (at Assets/scripts/GameManager.cs:38)

Any idea what the problem could be here? I cannot understand why calling 'Saver.Load' in the awake function works but calling the same function elsewhere doesn't. Thanks in advance.

**Comment by hasanbayatme** [comment]
Hi @dkorobov2.

You are using the old version of Save Game Free that needs initialization before saving and loading but in the Gold Update there is no need to do this.

Please use the updated Save Game Free version.

In the new version you can use Save system without initialization.

**Comment by dkorobov2** [comment]
I had to delete the old package and re-import. Everything is working now. Left a positive review and thanks for the help!

**Comment by hasanbayatme** [comment]
Thanks for reporting back.

You are awesome!
