### ISSUE TITLE
Loading with encoded bool

### ISSUE THREAD

**Issue by selmansavas** [BayatGames/SaveGameFree#3]
I can save a bool with a password, but i cant load it from file with same password. There is no documentation on loading the data, can you help me?

**Comment by hasanbayatme** [comment]
What error message you are receiving when doing load?

You just need to call SaveGame.Load method to load the specified identifier.

Thanks.

**Comment by selmansavas** [comment]
I wanted to enrypt saved data, i can encrypt it while saving, but i got problems on loading, but i figured it out. There really should be a documentation for using load functions too.

**Comment by hasanbayatme** [comment]
There are documentations about it on our website [BayatGames](https://bayatgames.com), but the website currently is suspended, so we are investigating to solve the issue.

Thanks.
