### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by alpapan** [BayatGames/SaveGameFree#8]
Hello 

the included 'documentation' files (pdf, rtf, doc, html) are not really a documentation, just an introduction that link to documents on the web. That would have been fine but sadly all the web links return 404.

e.g. `http://docs.bayat.io/scripting-api/savegame/save` etc

**Comment by hasanbayatme** [comment]
Hello.
You need check documentation at here: http://docs.bayat.io/savegamefree/
That URL you have used is wrong.

**Comment by EdProduction** [comment]
> Hello.
> You need check documentation at here: http://docs.bayat.io/savegamefree/
> That URL you have used is wrong.

yeah, that link is working, but manual and everything on it is not

**Comment by hasanbayatme** [comment]
I've checked the below links and all were fine:

http://docs.bayat.io/savegamefree/manual/
http://docs.bayat.io/savegamefree/scripting-api/
