### ISSUE TITLE
Identifiers not working en WebGL

### ISSUE THREAD

**Issue by Alvarden15** [BayatGames/SaveGameFree#9]
Hello. Not sure if anyone else has experienced this problem, but the identifiers stop working for some reason after importing another unrelated asset (might be coincidental, can't confirm, and those imported assets has nothing to do with saving, so it shouldn't be incompatibility issues), unabling me to load or save anything (i also tested the examples scenes and the problem appeared too). I tried re importing the asset, but it didn't solve anything. Delenting the other imported assets didn't help, either. 

Update: I found out the problem. After scratching my head for days, i decided to just switch Platform to the default WIndows and the identifiers worked again and it could save once move. So i doesn't have to do with any asset compatibility.... It just doesn't work with WebGL, so, there is still a problem (at least inside the editor, haven't tested it published). I tested it with other platforms, like Android and iOS, and they work too, being WebGL the only one which doesn't work. If anyone know the solution for this, let me know.

**Comment by otez-jedi** [comment]
@Alvarden15 this is because there's a double conversion of identifier to filepath happening. first time before checking for identifier existence, second time inside 'Exists' method after IsFilePath returned 'false' (it always returns 'false' on webgl).
that's my fix
![image](https://user-images.githubusercontent.com/14195321/95614819-6d80d100-0a67-11eb-8797-abe857570b56.png)
hope it helps

**Comment by Alvarden15** [comment]
> 
> 
> @Alvarden15 this is because there's a double conversion of identifier to filepath happening. first time before checking for identifier existence, second time inside 'Exists' method after IsFilePath returned 'false' (it always returns 'false' on webgl).
> that's my fix
> ![image](https://user-images.githubusercontent.com/14195321/95614819-6d80d100-0a67-11eb-8797-abe857570b56.png)
> hope it helps

@otez-jedi I appreciate the help, but the problem still persists. Is there another fix available for the asset?
